version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - type: bind
        source: ./page
        target: /usr/share/nginx/html
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - webnet

networks:
  webnet:
